# Generated by Django 3.0 on 2020-07-20 13:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comment_comments_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='commentReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('comment', models.TextField(max_length=500)),
                ('posted', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='posted',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comments_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Blog'),
        ),
        migrations.CreateModel(
            name='commentTrx',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Comment')),
                ('commentReply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.commentReply')),
            ],
        ),
        migrations.AddField(
            model_name='commentreply',
            name='comments_post',
            field=models.ManyToManyField(through='blog.commentTrx', to='blog.Comment'),
        ),
    ]
