# Generated by Django 3.0 on 2020-07-20 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200720_1431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commenttrx',
            name='Comment',
        ),
        migrations.RemoveField(
            model_name='commenttrx',
            name='commentReply',
        ),
        migrations.DeleteModel(
            name='commentReply',
        ),
        migrations.DeleteModel(
            name='commentTrx',
        ),
    ]
