# Generated by Django 3.0 on 2020-07-23 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200723_0619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentreply',
            name='comment_2_reply',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentreplies', to='blog.Comment'),
        ),
    ]
